foreground              #C3C6CF
background              #111418

# opacity
background_opacity 0.3

selection_foreground    #111418
selection_background    #C3C6CF
cursor                  #D7BEE4
cursor_text_color       #000000
active_tab_foreground   #111418
active_tab_background   #C3C6CF
inactive_tab_foreground #C3C6CF
inactive_tab_background #111418


# black
color0  #0B0E13
color8  #8D9199

# red
color1  #BA1A1A
color9  #FFDAD6

# green
color2  #8ABAE6
color10 #D7BEE4

# yellow
color3  #629CDD
color11 #A1CAFD

# blue
color4  #4F749E
color12 #33577C

# magenta
color5  #533F5F
color13 #F3DAFF

# cyan
color6  #BBC7DB
color14 #D7E3F8

# white
color7  #E1E2E8
color15 #F8F9FF
