# Main background
theme[main_bg]="#101C2B"

# Main text color
theme[main_fg]="#E1E2E8"

# Title color for boxes
theme[title]="#A1CAFD"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#D7BEE4"

# Background color of selected items
theme[selected_bg]="#1D2024"

# Foreground color of selected items
theme[selected_fg]="#E1E2E8"

# Color of inactive/disabled text
theme[inactive_fg]="#43474E"  

# Color of text appearing on top of graphs
theme[graph_text]="#C3C6CF"

# Misc colors for processes box
theme[proc_misc]="#3C4858"

# Cpu box outline color
theme[cpu_box]="#8D9199"

# Memory/disks box outline color
theme[mem_box]="#8D9199"

# Net up/down box outline color
theme[net_box]="#8D9199"

# Processes box outline color
theme[proc_box]="#8D9199"

# Box divider line and small boxes line color
theme[div_line]="#8D9199"

# Temperature graph colors
theme[temp_start]="#A1CAFD"
theme[temp_mid]="#1A4975"
theme[temp_end]="#A1CAFD"

# CPU graph colors
theme[cpu_start]="#629CDD"
theme[cpu_mid]="#629CDD"
theme[cpu_end]="#629CDD"

# Mem/Disk free meter
theme[free_start]="#3C4858"
theme[free_mid]="#BBC7DB"
theme[free_end]="#253140"

# Mem/Disk cached meter
theme[cached_start]="#BBC7DB"
theme[cached_mid]="#BBC7DB"
theme[cached_end]="#BBC7DB"

# Mem/Disk available meter
theme[available_start]="#253140"
theme[available_mid]="#D7E3F8"
theme[available_end]="#D7E3F8"

# Mem/Disk used meter
theme[used_start]="#3C4858"
theme[used_mid]="#BBC7DB"
theme[used_end]="#253140"

# Download graph colors
theme[download_start]="#629CDD"
theme[download_mid]="#A1CAFD"
theme[download_end]="#1A4975"

# Upload graph colors
theme[upload_start]="#1A4975"
theme[upload_mid]="#3C4858"
theme[upload_end]="#D7BEE4"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#D7BEE4"
theme[process_mid]="#533F5F"
theme[process_end]="#F3DAFF"
