-- DO NOT EDIT THIS FILE
return {
  {
    "sam4llis/nvim-tundra",
    name = "tundra",
    priority = 1000, -- make sure it loads first
    config = function()
      vim.cmd.colorscheme("tundra")
    end,
  },
}